//! CAN ECU EGS_SLAVE
//!
//! AUTOGENERATED by candb_codegen - DO NOT MODIFY.
//! Modify the can database instead

use super::SignalFrame;
use bitbybit::*;
use embedded_can::StandardId;

/// Can Frame DB SOLENOID_REPORT
#[bitfield(u64, defmt_bitfields)]
pub struct SolenoidReport {
    /// Recorded MPC Current
    #[bits(48..=63, rw)]
    pub mpc_curr: u16,
    /// Recorded SPC Current
    #[bits(32..=47, rw)]
    pub spc_curr: u16,
    /// Y3 solenoid on
    #[bit(31, rw)]
    pub y_3_on: bool,
    /// Y4 solenoid on
    #[bit(30, rw)]
    pub y_4_on: bool,
    /// Y5 solenoid on
    #[bit(29, rw)]
    pub y_5_on: bool,
    /// RP solenoid on
    #[bit(28, rw)]
    pub rp_on: bool,
    /// GPIO Mosfet on
    #[bit(27, rw)]
    pub gp_en: bool,
    /// Start output enabled
    #[bit(26, rw)]
    pub st_en: bool,
    /// Recorded TCC PWM
    #[bits(16..=23, rw)]
    pub tcc_pwm: u8,
    /// TRRS A state
    #[bit(15, rw)]
    pub trrs_a: bool,
    /// TRRS B state
    #[bit(14, rw)]
    pub trrs_b: bool,
    /// TRRS C state
    #[bit(13, rw)]
    pub trrs_c: bool,
    /// TRRS D state
    #[bit(12, rw)]
    pub trrs_d: bool,
    /// TRRS E state
    #[bit(11, rw)]
    pub trrs_e: bool,
    /// Total Recorded Current Div 10
    #[bits(0..=7, rw)]
    pub total_curr: u8,
}

impl SignalFrame for SolenoidReport {
    const CAN_ID: StandardId = unsafe { StandardId::new_unchecked(0x050A) };

    const LEN_BYTES: usize = 8;
}

crate::can_impl_code_gen!(SolenoidReport);

/// Can Frame DB SENSOR_REPORT
#[bitfield(u64, defmt_bitfields)]
pub struct SensorReport {
    /// Recorded N2 pulse count
    #[bits(48..=63, rw)]
    pub n_2_raw: u16,
    /// Recorded N3 pulse count
    #[bits(32..=47, rw)]
    pub n_3_raw: u16,
    /// Recorded Output pulse count
    #[bits(16..=31, rw)]
    pub out_raw: u16,
    /// Recorded battery voltage
    #[bits(8..=15, rw)]
    pub vbatt: u8,
    /// Recorded ATF Temperature (0xFF if Parking is engaged)
    #[bits(0..=7, rw)]
    pub tft: u8,
}

impl SignalFrame for SensorReport {
    const CAN_ID: StandardId = unsafe { StandardId::new_unchecked(0x050B) };

    const LEN_BYTES: usize = 8;
}

crate::can_impl_code_gen!(SensorReport);
