//! CAN Layer for slave_mode
//!
//! AUTOGENERATED by candb_codegen - DO NOT MODIFY.
//! Modify the can database instead

mod tester;
pub use tester::*;

mod egs_slave;
pub use egs_slave::*;

pub use super::SignalFrame;
