//! CAN ECU TESTER
//!
//! AUTOGENERATED by candb_codegen - DO NOT MODIFY.
//! Modify the can database instead

use super::SignalFrame;
use bitbybit::*;
use embedded_can::StandardId;

/// Can Frame DB SOLENOID_CONTROL
#[bitfield(u64, defmt_bitfields)]
pub struct SolenoidControl {
    /// MPC Current request
    #[bits(48..=63, rw)]
    pub mpc_req: u16,
    /// SPC Current request
    #[bits(32..=47, rw)]
    pub spc_req: u16,
    /// Enable Y3 solenoid
    #[bit(31, rw)]
    pub y_3_en: bool,
    /// Enable Y4 solenoid
    #[bit(30, rw)]
    pub y_4_en: bool,
    /// Enable Y5 solenoid
    #[bit(29, rw)]
    pub y_5_en: bool,
    /// Enable RP solenoid
    #[bit(28, rw)]
    pub rp_en: bool,
    /// Enable GPIO output
    #[bit(27, rw)]
    pub gp_en: bool,
    /// Enable start output
    #[bit(26, rw)]
    pub st_en: bool,
    /// TCC PWM request
    #[bits(16..=23, rw)]
    pub tcc_req: u8,
    /// PADDING
    #[bits(0..=15, rw)]
    pub reserved: u16,
}

impl SignalFrame for SolenoidControl {
    const CAN_ID: StandardId = unsafe { StandardId::new_unchecked(0x0501) };

    const LEN_BYTES: usize = 8;
}

crate::can_impl_code_gen!(SolenoidControl);
