use std::{collections::HashMap, path::PathBuf};

use crate::parser::{DataType, Frame};
use convert_case::{Case, Casing};
use std::fmt::Write as _;

pub struct EnumInfo {
    pub bit_size: usize,
    pub name: String,
    pub desc: String,
    pub frames: Vec<String>,
    pub tab: Vec<(u32, String, String)>
}

pub struct CodeGenerator {
    // List of ECUs and enums inside for that ECU
    // 1 ECU can have multiple frames with the same
    // enums
    enums: Vec<EnumInfo>,
    db: HashMap<String, Vec<Frame>>,
    out_path: PathBuf
}

impl CodeGenerator {
    pub fn new(db: HashMap<String, Vec<Frame>>, out_path: PathBuf) -> Self {
        let mut enum_tab: Vec<EnumInfo> = vec![];
        for (_ecu, frames) in db.iter() {
            for frame in frames {
                for signal in &frame.signals {
                    if let DataType::Enum(enum_) = &signal.dt {
                        if let Some(existing) = enum_tab.iter_mut().find(|x| {
                            x.name == signal.name
                        }) {
                            existing.frames.push(frame.name.clone());
                        } else {
                            enum_tab.push(EnumInfo { 
                                bit_size: signal.len as usize, 
                                name: signal.name.clone(), 
                                desc: signal.desc.clone(),
                                frames: vec![frame.name.clone()],
                                tab: enum_.clone() 
                            });
                        }
                    }
                }
            }
        }
        Self {
            enums: enum_tab,
            out_path,
            db
        }
    }

    pub fn code_gen(&self, layer_name: &String) -> std::fmt::Result {
        self.enum_gen();
        for (ecu, frames) in self.db.iter() {
            self.generate_ecu(ecu, frames);
        }
        // Generate MOD file
        let mut s = String::new();
        write!(s,
"
//! CAN Layer for {}
//! 
//! AUTOGENERATED by candb_codegen - DO NOT MODIFY. 
//! Modify the can database instead


", layer_name
)?;
        writeln!(s, "mod enums;")?;
        writeln!(s, "pub use enums::*;\n")?;
        for ecu in self.db.keys() {
            writeln!(s, "mod {};", ecu.to_case(Case::Snake))?;
            writeln!(s, "pub use {}::*;\n", ecu.to_case(Case::Snake))?;
        }

        writeln!(s, "pub use super::SignalFrame;")?;


        let mut mod_file = self.out_path.clone();
        mod_file.push("mod.rs");
        std::fs::write(mod_file, s.as_bytes()).unwrap();
        Ok(())
    }

    pub fn enum_gen(&self) {
        let mut s = String::new();
        s.push_str(
r#"
//! Enums used by CAN layer
//! 
//! AUTOGENERATED by candb_codegen - DO NOT MODIFY. 
//! Modify the can database instead

use bitbybit::*;

"#
);
        for en in self.enums.iter() {
            // Generate enum
            s.push_str(&self.generate_enum(en));
        }
        let mut enum_file = self.out_path.clone();
        enum_file.push("enums.rs");
        std::fs::write(enum_file, s.as_bytes()).unwrap();
    }

    // Check if an enum is safe (Contains all variants possible)
    pub fn check_enum_is_safe(len_bits: u32, tab: &[(u32, String, String)]) -> bool {
        let max_val = 2u32.pow(len_bits)-1; // Value with all bits set to 1s
        // Easy check, since we should just have as many variants as max_val+1 (to include 0) to indicate its safe
        tab.len() as u32 == max_val + 1
    }

    pub fn generate_ecu(&self, name: &String, frames: &[Frame]) {
        let mut s = String::new();

        let arb_int_req = frames.iter().any(|x| {
            x.signals.iter().any(|sig| {
                (sig.len != 1 && sig.len != 8 && sig.len != 16 && sig.len != 32 && sig.len != 64) && !matches!(sig.dt, DataType::Enum(_))
            })
        });
        let arb_int_import = if arb_int_req {
            "use arbitrary_int::*;"
        } else {
            ""
        };

        let enum_import_req = frames.iter().any(|x| {
            x.signals.iter().any(|sig| {
                matches!(sig.dt, DataType::Enum(_))
            })
        });
        let enum_import = if enum_import_req {
            "use super::enums::*;"
        } else {
            ""
        };


        s.push_str(&format!(
"
//! CAN ECU {}
//! 
//! AUTOGENERATED by candb_codegen - DO NOT MODIFY. 
//! Modify the can database instead

use mcan::embedded_can::{{Id, StandardId}};
use mcan::message::tx::{{AnyMessage, ClassicFrameType, FrameType, Message, MessageBuilder}};
use bitbybit::*;
{}
{}

", name, arb_int_import, enum_import
));

        for frame in frames {
            let frame_name = frame.name.to_case(Case::UpperCamel);
            let _ = writeln!(s, "/// Can Frame DB {}", frame.name);
            let _ = writeln!(s, "#[bitfield(u64, defmt_bitfields)]");
            let _ = writeln!(s, "pub struct {} {{", frame_name);
            
            // Definition
            for signal in &frame.signals {
                let (derrive_args, dt) = match &signal.dt {
                    DataType::Bool => (format!("#[bit({}, rw)]", 63-signal.offset), "bool".to_string()),
                    DataType::Int { offset:_, multi:_ } => {
                        let fmt = format!("#[bits({}..={}, rw)]", (64-signal.offset-signal.len), 63-signal.offset);
                        let ty = format!("u{}", signal.len);
                        (fmt, ty)

                    },
                    DataType::Enum(tab) => {
                        let ty = if Self::check_enum_is_safe(signal.len, tab) {
                            format!("Enum{}",signal.name.clone())
                        } else {
                            format!("Option<Enum{}>", signal.name.clone())
                        };
                        (format!("#[bits({}..={}, rw)]", (64-signal.offset-signal.len), 63-signal.offset), ty)
                    },
                    DataType::IsoTp => {
                        let bytes = signal.len / 8;
                        ("#[bits(0..=7, rw)]".to_string(), format!("[u8; {bytes}]"))
                    },
                };

                let _ = writeln!(s, "\t/// {}", signal.desc);
                let _ = writeln!(s, "\t{}", derrive_args);
                let _ = writeln!(s, "\tpub {}: {},", signal.name.to_case(Case::Snake), dt);
            }
            let _ = writeln!(s, "}}\n");

            // Impl (CAN ID)
            let _ = writeln!(s, "impl super::SignalFrame for {} {{", frame_name);
            let _ = writeln!(s, "\tconst CAN_ID: Id = unsafe {{ Id::Standard(StandardId::new_unchecked(0x{:04X})) }};", frame.id);
            let _ = writeln!(s, "\tfn as_tx_can_msg(&self) -> mcan::message::tx::Message<64> {{");
            let n_bytes = frame.signals.last().map(|x| {
                ((x.len + x.offset) / 8) as usize
            }).unwrap_or(8);
            let _ = writeln!(s, "\t\tlet bytes = &self.raw_value().to_be_bytes()[..{n_bytes}];");
            let _ = writeln!(s, "\t\tMessage::new(MessageBuilder {{");
            let _ = writeln!(s, "\t\t\tid: Self::CAN_ID,");
            let _ = writeln!(s, "\t\t\tframe_type: FrameType::Classic(ClassicFrameType::Data(bytes)),");
            let _ = writeln!(s, "\t\t\tstore_tx_event: None,");
            let _ = writeln!(s, "\t\t}})");
            let _ = writeln!(s, "\t\t.unwrap()");
            let _ = writeln!(s, "\t}}");
            let _ = writeln!(s, "}}\n");
        }

        let mut ecu_file = self.out_path.clone();
        ecu_file.push(format!("{}.rs", name.to_case(Case::Snake).trim()));
        std::fs::write(ecu_file, s.as_bytes()).unwrap();
    }

    pub fn generate_enum(&self, entry: &EnumInfo) -> String {
        let mut s = String::new();
        let derrive_ty = format!("u{}", entry.bit_size);
        let is_safe = Self::check_enum_is_safe(entry.bit_size as u32, &entry.tab);
        if entry.frames.len() == 1 {
            let _ = writeln!(s, "/// Can Frame {}: {}", entry.frames[0], entry.desc);
        } else {
            let _ = writeln!(s, "/// Can Frames {:?}: {}", entry.frames, entry.desc);
        }
        let _ = writeln!(s, "#[derive(defmt::Format)]");
        let _ = writeln!(s, "#[bitenum({}, exhaustive={})]", derrive_ty, is_safe);
        let _ = writeln!(s, "pub enum Enum{} {{", entry.name);
        for val in &entry.tab {
            let _ = writeln!(s, "\t/// {}", val.2); // Description comment
            let _ = writeln!(s, "\t{} = {},", val.1, val.0); // Value
        }
        let _ = writeln!(s, "}}\n");

        s
    }
}