//! Enums used by CAN layer
//!
//! AUTOGENERATED by candb_codegen - DO NOT MODIFY.
//! Modify the can database instead

use bitbybit::*;

/// Can Frame HFM_210h: shifter module code
#[derive(defmt::Format)]
#[bitenum(u4, exhaustive = false)]
pub enum EnumWhc {
    /// driving position P/N engaged (automatic transmission only)
    PnB = 0,
    /// driving position reverse
    RB = 3,
    /// driving position P/N not engaged (automatic transmission only)
    D4B = 5,
    /// manual transmission
    Sch = 10,
}

/// Can Frame HFM_308h: HFM coding
#[derive(defmt::Format)]
#[bitenum(u8, exhaustive = false)]
pub enum EnumHfmCod {
    /// M111 E22, model series 202
    Br202E22 = 40,
    /// M111 E22, model series 124 w/ partial intake manifold preheating
    Br124E22Mpsv = 41,
    /// M111 E22, model series 124 wo/ partial intake manifold preheating
    Br124E22Opsv = 42,
    /// M104 E32, model series 202
    Br202E32 = 60,
    /// M104 E32, model series 124
    Br124E32 = 61,
    /// M104 E32, model series 140
    Br140E32 = 62,
    /// M104 E32, model series 129
    Br129E32 = 63,
    /// M104 E32, model series 210
    Br210E32 = 64,
    /// M104 E28, model series 202
    Br202E28 = 65,
    /// M104 E28, model series 124
    Br124E28 = 66,
    /// M104 E28, model series 140
    Br140E28 = 67,
    /// M104 E28, model series 129
    Br129E28 = 68,
    /// M104 E28, model series 210
    Br210E28 = 69,
    /// M104 E32, flexible fuel engine
    Ffve32 = 72,
    /// M104 E32, model series 140, functional testing
    Br140E32Fe = 82,
}
