//! CAN ECU HFM
//!
//! AUTOGENERATED by candb_codegen - DO NOT MODIFY.
//! Modify the can database instead

use super::SignalFrame;
use bitbybit::*;
use embedded_can::StandardId;

use super::enums::*;

/// Can Frame DB HFM_210h
#[bitfield(u64, defmt_bitfields)]
pub struct Hfm210H {
    /// shifter module code
    #[bits(57..=60, rw)]
    pub whc: Option<EnumWhc>,
    /// throttle valve actual value
    #[bits(48..=55, rw)]
    pub dki: u8,
    /// throttle valve target value
    #[bits(40..=47, rw)]
    pub dkv: u8,
    /// vehicle speed
    #[bits(32..=39, rw)]
    pub v_signal: u8,
    /// emergency mode
    #[bit(30, rw)]
    pub notl_b: bool,
    /// brake light switch on
    #[bit(29, rw)]
    pub bls_b: bool,
    /// full throttle
    #[bit(26, rw)]
    pub vg_b: bool,
    /// vehicle speed signal implausible
    #[bit(22, rw)]
    pub vsig_up_b: bool,
    /// throttle valve target value implausible
    #[bit(17, rw)]
    pub dkv_up_b: bool,
    /// throttle valve actual value implausible
    #[bit(16, rw)]
    pub dki_up_b: bool,
}

impl SignalFrame for Hfm210H {
    const CAN_ID: StandardId = unsafe { StandardId::new_unchecked(0x0210) };

    const LEN_BYTES: usize = 6;
}

crate::can_impl_code_gen!(Hfm210H);

/// Can Frame DB HFM_308h
#[bitfield(u64, defmt_bitfields)]
pub struct Hfm308H {
    /// engine speed implausible
    #[bit(56, rw)]
    pub nmot_up_b: bool,
    /// HFM coding
    #[bits(48..=55, rw)]
    pub hfm_cod: Option<EnumHfmCod>,
    /// engine speed
    #[bits(32..=47, rw)]
    pub nmot: u16,
    /// air mass signal implausible
    #[bit(23, rw)]
    pub hfm_up_b: bool,
    /// starter running
    #[bit(16, rw)]
    pub kl_50_b: bool,
}

impl SignalFrame for Hfm308H {
    const CAN_ID: StandardId = unsafe { StandardId::new_unchecked(0x0308) };

    const LEN_BYTES: usize = 6;
}

crate::can_impl_code_gen!(Hfm308H);

/// Can Frame DB HFM_608h
#[bitfield(u64, defmt_bitfields)]
pub struct Hfm608H {
    /// engine temperature
    #[bits(56..=63, rw)]
    pub t_mot: u8,
    /// engine temperature implausible
    #[bit(47, rw)]
    pub tfm_up_b: bool,
    /// intake air temperature implausible
    #[bit(46, rw)]
    pub tfa_up_b: bool,
    /// intake air temperature
    #[bits(16..=23, rw)]
    pub t_luft: u8,
}

impl SignalFrame for Hfm608H {
    const CAN_ID: StandardId = unsafe { StandardId::new_unchecked(0x0608) };

    const LEN_BYTES: usize = 6;
}

crate::can_impl_code_gen!(Hfm608H);

/// Can Frame DB HFM_610h
#[bitfield(u64, defmt_bitfields)]
pub struct Hfm610H {
    /// ROZ tempering detection
    #[bit(32, rw)]
    pub roz_tp_b: bool,
    /// air mass flow
    #[bits(16..=23, rw)]
    pub mle: u8,
}

impl SignalFrame for Hfm610H {
    const CAN_ID: StandardId = unsafe { StandardId::new_unchecked(0x0610) };

    const LEN_BYTES: usize = 6;
}

crate::can_impl_code_gen!(Hfm610H);
