//! CAN Layer for hfm_can
//!
//! AUTOGENERATED by candb_codegen - DO NOT MODIFY.
//! Modify the can database instead

mod enums;
pub use enums::*;

mod hfm;
pub use hfm::*;

pub use super::SignalFrame;
